<a href="https://colab.research.google.com/github/Siddanth-tech/Eda-25BAI0031/blob/main/assignment%204.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data=np.arange(10,20).reshape(5,2)
df=pd.DataFrame(data,index=['a','b','c','d','e'],columns=['grp1','grp2'])
df

   grp1  grp2
a    10    11
b    12    13
c    14    15
d    16    17
e    18    19

In [4]:
df['grp1']=np.nan
df.loc['b']=np.nan
df.loc['d']=np.arange(1,3)
df['grp1']['a']=67
df

/tmp/ipykernel_3585/3530964106.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['grp1']['a']=67

   grp1  grp2
a  67.0  11.0
b   NaN   NaN
c   NaN  15.0
d   1.0   2.0
e   NaN  19.0

In [7]:
df.isnull()

    grp1   grp2
a  False  False
b   True   True
c   True  False
d  False  False
e   True  False

In [8]:
df.notnull()

    grp1   grp2
a   True   True
b  False  False
c  False   True
d   True   True
e  False   True

In [9]:
df.isnull().sum()

grp1    3
grp2    1
dtype: int64

In [10]:
df.isnull().sum().sum()

np.int64(4)

In [11]:
df.count()

grp1    2
grp2    4
dtype: int64

In [12]:
df.grp1[df.grp1.notnull()]

a    67.0
d     1.0
Name: grp1, dtype: float64

In [13]:
df.grp1.dropna()

a    67.0
d     1.0
Name: grp1, dtype: float64

In [14]:
df.dropna()

   grp1  grp2
a  67.0  11.0
d   1.0   2.0

this drops all rows which has nan values

In [15]:
df.dropna(how='all')

   grp1  grp2
a  67.0  11.0
c   NaN  15.0
d   1.0   2.0
e   NaN  19.0

this drops only rows with all nan

In [16]:
df.dropna(how='all',axis=1)

   grp1  grp2
a  67.0  11.0
b   NaN   NaN
c   NaN  15.0
d   1.0   2.0
e   NaN  19.0

checks column instead of rows

In [17]:
df.dropna(thresh=3,axis=1)

   grp2
a  11.0
b   NaN
c  15.0
d   2.0
e  19.0

this checks the minm no. of nan to be, then only drops

In [22]:
ar=np.array([10,20,np.nan,30])
ar

array([10., 20., nan, 30.])

In [23]:
ser1=pd.Series(ar)
ser1

0    10.0
1    20.0
2     NaN
3    30.0
dtype: float64

In [20]:
ar.mean()

np.float64(nan)

In [24]:
ser1.mean()

np.float64(20.0)

In [25]:
ser2=df.grp2

In [26]:
ser2.sum()

np.float64(47.0)

In [27]:
ser2.cumsum()#cumulative

a    11.0
b     NaN
c    26.0
d    28.0
e    47.0
Name: grp2, dtype: float64

In [30]:
filledDf=df.fillna(0)
filledDf

   grp1  grp2
a  67.0  11.0
b   0.0   0.0
c   0.0  15.0
d   1.0   2.0
e   0.0  19.0

In [31]:
filledDf.mean()

grp1    13.6
grp2     9.4
dtype: float64

In [32]:
df.grp1.fillna(method='ffill')

/tmp/ipykernel_3585/1850045838.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.grp1.fillna(method='ffill')

a    67.0
b    67.0
c    67.0
d     1.0
e     1.0
Name: grp1, dtype: float64

this copies value of previous value and paste onto nan

In [33]:
df.grp1.fillna(method='bfill')

/tmp/ipykernel_3585/896691082.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.grp1.fillna(method='bfill')

a    67.0
b     1.0
c     1.0
d     1.0
e     NaN
Name: grp1, dtype: float64